---
- name: Create galaxy config file for lite start
  copy:
    src: '{{ galaxy_config_path }}/galaxy.{{galaxy_config_file_extension}}.sample'
    dest: '{{ galaxy_config_path }}/galaxy.{{galaxy_config_file_extension}}.lite'
    remote_src: true

- name: 'Get database_connection from {{ galaxy_config_file }}.prod'
  command: '{{ galaxy_venv_path }}/bin/python /tmp/read_galaxy_config_file.py -c {{ galaxy_config_path }}/galaxy.{{galaxy_config_file_extension}}.prod -s {{galaxy_main_section}} -o database_connection'
  register: galaxy_database_connection

- name: 'Get install_database_connection from {{ galaxy_config_file }}.prod'
  command: '{{ galaxy_venv_path }}/bin/python /tmp/read_galaxy_config_file.py -c {{ galaxy_config_path }}/galaxy.{{galaxy_config_file_extension}}.prod -s {{galaxy_main_section}} -o install_database_connection'
  register: galaxy_install_database_connection

- name: 'Get admin_users from {{ galaxy_config_file }}.prod'
  command: '{{ galaxy_venv_path }}/bin/python /tmp/read_galaxy_config_file.py -c {{ galaxy_config_path }}/galaxy.{{galaxy_config_file_extension}}.prod -s {{galaxy_main_section}} -o admin_users'
  register: galaxy_admin_users

- name: edit galaxy.ini.lite
  ini_file:
    dest: '{{ galaxy_config_path}}/galaxy.ini.lite'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: 'app:main', option: 'database_connection', value: '{{galaxy_database_connection.stdout}}' }
    - { section: 'app:main', option: 'install_database_connection', value: '{{galaxy_install_database_connection.stdout}}' }
    - { section: 'app:main', option: 'admin_users', value: '{{galaxy_admin_users.stdout}}' }
  when: galaxy_config_file_extension == 'ini'

- name: edit galaxy.yml.lite
  command: '{{ galaxy_venv_path }}/bin/python
            {{ galaxy_custom_script_path }}/parse_galaxy_yaml.py
            -c "{{ galaxy_config_path }}/galaxy.yml.lite"
            -s "{{ item.section }}"
            -o "{{ item.option }}"
            -v "{{ item.value }}"'
  with_items:
    - { section: 'galaxy', option: 'database_connection', value: '{{galaxy_database_connection.stdout}}' }
    - { section: 'galaxy', option: 'install_database_connection', value: '{{galaxy_install_database_connection.stdout}}' }
    - { section: 'galaxy', option: 'admin_users', value: '{{galaxy_admin_users.stdout}}' }
  when: galaxy_config_file_extension == 'yml'
