---
- set_fact:
    galaxyctl_bin_path: '/usr/bin'
  when: ansible_os_family == "RedHat"

- set_fact:
    galaxyctl_bin_path: '/usr/local/bin'
  when: ansible_os_family == "Debian"

# Copy script to read galaxy config file
- name: Copy galaxy configuration file reader
  gat_url:
    url: 'https://raw.githubusercontent.com/Laniakea-elixir-it/Scripts/master/galaxy/read_galaxy_config_file.py'
    dest: '/tmp/read_galaxy_config_file.py'
    mode: a+x

# Check galaxy.ini or galaxy.yml to enable support for older versions
- name: Check that the galaxy.yml exists
  stat:
    path: '{{ galaxy_config_path }}/galaxy.yml'
    register: stat_result

- name: Set galaxy_config_file to galaxy.ini if galaxy.yml not exists
  set_fact:
    galaxy_config_file: '{{ galaxy_config_path }}/galaxy.ini'
  when: not stat_resutl.stat.exists|bool

# Ansible galaxy is not capable to download git submodules. We clone here Galaxy-flavor-recipes in {{galaxy_tools_base_dir}}
- name: 'Create {{ galaxy_tools_base_dir }}'
  file:
    path: '{{ galaxy_tools_base_dir }}'
    state: directory

- name: Get Galaxy flavor recipes
  git:
    repo: 'https://github.com/indigo-dc/Galaxy-flavors-recipes.git'
    clone: yes
    force: yes
    dest: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes'
    version: '{{ Galaxy_flavor_recipe_branch }}'

- name: Include sources list
  include: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{galaxy_flavor}}/{{galaxy_flavor}}-sources-list.yml'

- include: create_bootstrap_user.yml
  when: create_bootstrap_user|bool
  become_user: '{{galaxy_user}}'
  become: yes

- include: tools.yml

- include: interactive_tours.yml
  when: install_interactive_tours|bool

- include: workflows_and_libraries.yml
  when: install_workflows|bool or install_data_libraries|bool

- include: assets.yml
  when: add_more_assets|bool

- include: delete_bootstrap_user.yml
  when: create_bootstrap_user|bool
  become_user: '{{galaxy_user}}'
  become: yes

- name: Lock role
  template:
    src: 'indigo-dc.galaxycloud-tools.lock.j2'
    dest: '{{lock_file_path}}/indigo-dc.galaxycloud-tools.lock'
