---
# Ansible galaxy is not capable to download git submodules. We clone here Galaxy-flavor-recipes in /tmp
- name: Get Galaxy flavor recipes
  git:
    repo: 'https://github.com/indigo-dc/Galaxy-flavors-recipes.git'
    clone: yes
    force: yes
    dest: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes'

- name: Include sources list
  include: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{galaxy_flavor}}/{{galaxy_flavor}}-sources-list.yml'

- include: tools.yml

- include: interactive_tours.yml
  when: install_interactive_tours|bool

- include: workflows_and_libraries.yml
  when: install_workflows|bool or install_data_libraries|bool

- name: Lock role
  template:
    src: 'indigo-dc.galaxycloud-tools.lock.j2'
    dest: '{{lock_file_path}}/indigo-dc.galaxycloud-tools.lock'
