---
# Ansible galaxy is not capable to download git submodules. We clone here Galaxy-flavor-recipes in /tmp
- name: Get Galaxy flavor recipes
  git:
    repo: 'https://github.com/indigo-dc/Galaxy-flavors-recipes.git'
    clone: yes
    force: yes
    dest: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes'

- include: tools.yml
