---
#______________________________________
# Galaxyctl facts
- set_fact:
    galaxyctl_bin_path: '/usr/bin'
  when: ansible_os_family == "RedHat"

- set_fact:
    galaxyctl_bin_path: '/usr/local/bin'
  when: ansible_os_family == "Debian"

#______________________________________
# Copy script to read galaxy config file
- name: Copy galaxy configuration file reader
  get_url:
    url: 'https://raw.githubusercontent.com/Laniakea-elixir-it/Scripts/master/galaxy/read_galaxy_config_file.py'
    dest: '/tmp/read_galaxy_config_file.py'
    mode: a+x

#______________________________________
# get galaxy version number to support for older galaxy versione (<18.01) when ini file was used

- name: Get Galaxy version number only for comparison
  set_fact:
    galaxy_version_number: "{{ GALAXY_VERSION | replace('release_','') }}"
  when: (GALAXY_VERSION != 'master') or (GALAXY_VERSION != 'dev')

- debug:
    msg: 'Galaxy version: {{ GALAXY_VERSION }}'

- debug:
    msg: 'Galaxy version number: {{ galaxy_version_number }}'
  when: galaxy_version_number is defined

#______________________________________
# Check galaxy.ini or galaxy.yml to enable support for older versions

- name: Check that the galaxy.yml.sample exists
  stat:
    path: '{{ galaxy_config_path }}/galaxy.yml.sample'
  register: stat_result

- name: 'Set galaxy.yml extension to yml for conditionals'
  set_fact:
    galaxy_config_file_extension: 'yml'
    galaxy_main_section: 'galaxy'
  when: stat_result.stat.exists|bool

- name: Set galaxy_config_file to galaxy.ini if galaxy.yml not exists
  set_fact:
    galaxy_config_file: '{{ galaxy_config_path }}/galaxy.ini'
    galaxy_config_file_extension: 'ini'
    galaxy_main_section: 'app:main'
  when: not stat_result.stat.exists|bool

#______________________________________
# Ansible galaxy is not able to download git submodules.
# We clone here Galaxy-flavor-recipes in {{galaxy_tools_base_dir}}
- name: 'Create {{ galaxy_tools_base_dir }}'
  file:
    path: '{{ galaxy_tools_base_dir }}'
    state: directory

- name: Get Galaxy flavor recipes
  git:
    repo: '{{ galaxy_flavor_recipe_repository }}'
    clone: yes
    force: yes
    dest: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes'
    version: '{{ galaxy_flavor_recipe_branch }}'

- name: Include sources list
  include: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{galaxy_flavor}}/{{galaxy_flavor}}-sources-list.yml'

#______________________________________
- include: create_bootstrap_user.yml
  when: create_bootstrap_user|bool
  become_user: '{{galaxy_user}}'
  become: yes

- include: tools.yml

- include: interactive_tours.yml
  when: install_interactive_tours|bool

- include: workflows_and_libraries_17.yml
  when:
   - (galaxy_version_number is defined) and (galaxy_version_number|float < 18.01) 
   - (install_workflows|bool) or (install_data_libraries|bool)

- include: workflows_and_libraries.yml
  when:
   - (GALAXY_VERSION == 'master') or (GALAXY_VERSION == 'dev') or (galaxy_version_number|float >= 18)
   - (install_workflows|bool) or (install_data_libraries|bool)

- include: assets.yml
  when: add_more_assets|bool

- include: delete_bootstrap_user.yml
  when: create_bootstrap_user|bool
  become_user: '{{galaxy_user}}'
  become: yes

#______________________________________
- name: Lock role
  template:
    src: 'indigo-dc.galaxycloud-tools.lock.j2'
    dest: '{{lock_file_path}}/indigo-dc.galaxycloud-tools.lock'
