---
- name: '[EL] Install script dependencies'
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - lsof
  when: ansible_os_family == "RedHat"

- name: '[Ubuntu] Install dependencies'
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - lsof
  when: ansible_os_family == "Debian"

- name: Copy the install-tools script
  template:
    src: 'install-tools.sh.j2'
    dest: '{{galaxy_custom_script_path}}/install-tools'
    mode: a+x

- include: '{{ galaxy_tools_base_dir }}/Galaxy-flavors-recipes/{{galaxy_flavor}}/{{galaxy_flavor}}-sources-list.yml'

- include: install_tool_list.yml
  with_items: '{{ galaxy_tools_tool_list_files }}'
  loop_control:
    loop_var: tool_list_file
