---
- name: 'Ensure galaxy is running'
  supervisorctl: name="galaxy:" state=started
  ignore_errors: yes  

- name: 'Create/invoke script virtualenv'
  pip:
    name: '{{ item }}'
    virtualenv: '{{ tools_venv_dir }}'
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    state: forcereinstall
  with_items:
    - ephemeris=={{ephemeris_version}}
  when:  (GALAXY_VERSION == 'master') or (GALAXY_VERSION == 'dev') or (galaxy_version_number|float >= 18)

# If the bootstrap user is used, it will be deleted.
# Workflows are installed at user level and will be deleted, too.
# So we skip workflow installation.
- include: install_workflow_list.yml
  with_items: '{{ galaxy_tools_workflow_list_path }}'
  loop_control:
    loop_var: workflow_list_path
  when:
    - install_workflows|bool
    - not create_bootstrap_user|bool

# Data libraries upload is Currently not working
# TODO fix.
#- include: install_data_library_list.yml
#  with_items: '{{ galaxy_tools_data_library_list_files }}'
#  loop_control:
#    loop_var: data_library_list_file
#  when:
#    - install_data_libraries|bool
#    - not create_bootstrap_user|bool

#______________________________________
# Move datasets if src dir exists
- name: 'Check if /home/galaxy/galaxy/database/files dir exists'
  stat:
    path: '{{galaxy_install_path}}/database/files/'
  register: home_galaxy_database_dir

- include: move_datasets.yml
  when:
    - move_datasets|bool
    - home_galaxy_database_dir.stat.exists

- name: restore galaxy configuration file
  copy:
    src: '{{galaxy_config_path}}/galaxy.prod.{{galaxy_config_file_extension}}'
    dest: '{{galaxy_config_file}}'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
    remote_src: true
