---
- name: stop galaxy
  supervisorctl: name="galaxy:" state=stopped
  ignore_errors: yes

- name: backup galaxy.ini
  copy:
    src: '{{galaxy_config_file}}'
    dest: '{{galaxy_config_path}}/galaxy.ini.prod'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
    remote_src: true
    force: no # prevent galaxy.ini.prod be rewritten

- include: create_galaxy_ini_lite.yml 

- name: Move to lite galaxy.ini file
  copy:
    src: '{{galaxy_config_path}}/galaxy.ini.lite'
    dest: '{{galaxy_config_file}}'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
    remote_src: true

- name: Copy galaxy-startup-lite script
  template:
    src: 'galaxy-startup-lite.sh.j2'
    dest: '{{galaxy_custom_script_path}}/galaxy-startup-lite'
    mode: a+x

- name: Start Galaxy lite
  command: '{{galaxy_custom_script_path}}/galaxy-startup-lite start'

- name: Create/invoke script virtualenv
  pip:
    name: '{{ item }}'
    virtualenv: '{{ galaxy_tools_base_dir }}/venv'
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    state: forcereinstall
  with_items:
    - ephemeris

- include: install_workflow_list.yml
  with_items: '{{ galaxy_tools_workflow_list_path }}'
  loop_control:
    loop_var: workflow_list_path
  when: install_workflows|bool

- include: install_data_library_list.yml
  with_items: '{{ galaxy_tools_data_library_list_files }}'
  loop_control:
    loop_var: data_library_list_file
  when: install_data_libraries|bool

- name: Stop Galaxy lite
  command: '{{galaxy_custom_script_path}}/galaxy-startup-lite stop'

- inclide: move_libraries.yml

- name: restore galaxy.ini
  copy:
    src: '{{galaxy_config_path}}/galaxy.ini.prod'
    dest: '{{galaxy_config_file}}'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
    remote_src: true
