---
- name: stop galaxy
  supervisorctl: name="galaxy:" state=stopped
  ignore_errors: yes

- name: backup galaxy config file
  copy:
    src: '{{galaxy_config_file}}'
    dest: '{{galaxy_config_path}}/galaxy.{{galaxy_config_file_extension}}.prod'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
    remote_src: true
    force: no # prevent galaxy.yml.prod be rewritten

- include: create_galaxy_config_lite.yml 

- name: Move to lite galaxy configuration file file
  copy:
    src: '{{galaxy_config_path}}/galaxy.{{galaxy_config_file_extension}}.lite'
    dest: '{{galaxy_config_file}}'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
    remote_src: true

- name: '[release_17.**] Copy galaxy-startup-lite script'
  template:
    src: 'galaxy-startup-lite.17.sh.j2'
    dest: '{{galaxy_custom_script_path}}/galaxy-startup-lite'
    mode: a+x
  when: (galaxy_version_number is defined) and (galaxy_version_number|float < 18.01)

- name: '[release_18.**] Copy the galaxy-startup-lite script'
  template:
    src: 'galaxy-startup-lite.sh.j2'
    dest: '{{galaxy_custom_script_path}}/galaxy-startup-lite'
    mode: a+x
  when:  (GALAXY_VERSION == 'master') or (GALAXY_VERSION == 'dev') or (galaxy_version_number|float >= 18)

- name: Start Galaxy lite
  shell: '{{galaxy_custom_script_path}}/galaxy-startup-lite start >> /tmp/galaxy_startup_lite.log'

- name: Create/invoke script virtualenv
  pip:
    name: '{{ item }}'
    virtualenv: '{{ tools_venv_dir }}'
    virtualenv_command: "{{ pip_virtualenv_command | default( 'virtualenv' ) }}"
    state: forcereinstall
  with_items:
    - ephemeris=={{ephemeris_version}}

# If the bootstrap user is used, it will be deleted.
# Workflows are installed at user level and will be deleted, too.
# So we skip workflow installation.
- include: install_workflow_list.yml
  with_items: '{{ galaxy_tools_workflow_list_path }}'
  loop_control:
    loop_var: workflow_list_path
  when:
    - install_workflows|bool
    - not create_bootstrap_user|bool

- include: install_data_library_list.yml
  with_items: '{{ galaxy_tools_data_library_list_files }}'
  loop_control:
    loop_var: data_library_list_file
  when:
    - install_data_libraries|bool
    - not create_bootstrap_user|bool

- name: Stop Galaxy lite
  shell: '{{galaxy_custom_script_path}}/galaxy-startup-lite stop >> /tmp/galaxy_startup_lite.log'

#______________________________________
# Move datasets if src dir exists
- name: 'Check if /home/galaxy/galaxy/database/files dir exists'
  stat:
    path: '{{galaxy_install_path}}/database/files/'
  register: home_galaxy_database_dir

- include: move_datasets.yml
  when:
    - move_datasets|bool
    - home_galaxy_database_dir.stat.exists

- name: restore galaxy configuration file
  copy:
    src: '{{galaxy_config_path}}/galaxy.{{galaxy_config_file_extension}}.prod'
    dest: '{{galaxy_config_file}}'
    owner: '{{galaxy_user}}'
    group: '{{galaxy_user}}'
    remote_src: true
