---
- name: Set galaxy restart command
  set_fact:
    galaxy_restart: "{{ galaxy_custom_script_path }}/galaxyctl restart galaxy --force"

- name: 'Restart Galaxy'
  command: '{{ galaxy_restart }}'
  ignore_errors: yes

- name: 'Check if Galaxy is on line'
  uri:
    url: '{{ galaxy_instance_url }}'
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
